volumes:
  mysql_data:

services:
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"

  mysql:
    image: mariadb:10
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: foobar

  wordpress:
    image: thedxw/wpc-wordpress:php8.2
    ports:
      - "80:80"
    links:
      - mysql
      - mailcatcher
    volumes:
      - .:/usr/src/app
      - ./wp-content:/var/www/html/wp-content
