#!/bin/sh
set -e

exec docker-compose exec wordpress bash -c "cd ./wp-content/themes/\$(/usr/local/bin/wp theme list --status=active --field=name | cut -d\"/\" -f1) && vendor/bin/php-cs-fixer -v fix && vendor/bin/kahlan spec"
