#!/bin/sh
set -e

THEME_DIRECTORY="./wp-content/themes/theme"

echo "===> Linting shell scripts..."

./.shellcheck.sh

echo "===> Linting theme files..."

$THEME_DIRECTORY/vendor/bin/php-cs-fixer fix --dry-run -v --diff  --config="$THEME_DIRECTORY/.php-cs-fixer.php"

echo "===> Validating Whippet files..."
vendor/bin/whippet deps validate

echo "===> Running theme unit tests..."
$THEME_DIRECTORY/vendor/bin/kahlan --spec="$THEME_DIRECTORY/spec"
